#!/bin/bash
#===============================================================================
# BOOTSTRAP REPO SCRIPT - "Ghost Protocol"
# One-shot repository creation with dry-run and auto-cleanup
# 
# Usage: ./bootstrap-repo.sh <repo-name> [--dry-run] [--private]
#===============================================================================

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

#-------------------------------------------------------------------------------
# Configuration
#-------------------------------------------------------------------------------
PROJ="${1:-}"
DRY_RUN="${2:-}"
VISIBILITY="${3:---public}"
TEMP_BASE="${TMPDIR:-/data/data/com.termux/files/home/.tmp}/repo-bootstrap-$$"
mkdir -p "${TEMP_BASE%/*}" 2>/dev/null || true

#-------------------------------------------------------------------------------
# Helper Functions
#-------------------------------------------------------------------------------
log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_step()    { echo -e "${CYAN}[STEP]${NC} $1"; }

check_deps() {
    local missing=()
    for cmd in git gh; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing dependencies: ${missing[*]}"
        log_info "Install with: pkg install git gh (Termux) or brew install git gh (macOS)"
        exit 1
    fi
}

validate_project_name() {
    local name="$1"
    if [[ ! "$name" =~ ^[a-z][a-z0-9_-]*$ ]]; then
        log_error "Invalid project name. Use lowercase letters, numbers, hyphens, underscores."
        exit 1
    fi
}

cleanup() {
    if [[ "$DRY_RUN" != "--dry-run" ]] && [[ -d "$TEMP_BASE" ]]; then
        log_step "Cleaning up temporary files..."
        rm -rf "$TEMP_BASE"
        log_success "Ghost protocol engaged - no traces left behind"
    fi
}

trap cleanup EXIT

#-------------------------------------------------------------------------------
# Main Logic
#-------------------------------------------------------------------------------
main() {
    # Validate input
    if [[ -z "$PROJ" ]]; then
        log_error "Usage: $0 <repo-name> [--dry-run] [--private]"
        log_info "Example: $0 video-play --dry-run"
        exit 1
    fi

    validate_project_name "$PROJ"
    check_deps

    log_step "Initializing bootstrap sequence for: ${PROJ}"
    log_info "Visibility: ${VISIBILITY}"
    [[ "$DRY_RUN" == "--dry-run" ]] && log_warn "DRY RUN MODE - No remote changes"

    # Create temporary build directory
    BUILD_DIR="${TEMP_BASE}/${PROJ}"
    mkdir -p "${BUILD_DIR}"
    log_step "Building architecture in: ${BUILD_DIR}"

    #---------------------------------------------------------------------------
    # 1. Create Directory Structure
    #---------------------------------------------------------------------------
    log_step "Creating directory structure..."
    mkdir -p "${BUILD_DIR}"/{scripts,docs,help,files,assets,src,tests,.github/workflows}

    #---------------------------------------------------------------------------
    # 2. Create index.html in every directory (web-routing/privacy)
    #---------------------------------------------------------------------------
    log_step "Deploying index.html files..."
    find "${BUILD_DIR}" -type d -exec sh -c 'echo "<!-- Protected -->" > {}/index.html' \;

    #---------------------------------------------------------------------------
    # 3. Generate Quality Markdown Content
    #---------------------------------------------------------------------------
    log_step "Generating documentation..."

    # README.md
    cat > "${BUILD_DIR}/README.md" <<EOF
# ${PROJ^^}

> Automated Repository - Generated by Bootstrap Script

## Status

| Component | Status |
|-----------|--------|
| Structure | ✅ Complete |
| Docs | ✅ Scaffolded |
| CI/CD | ⏳ Pending |
| Tests | ⏳ Pending |

## Quick Start

\`\`\`bash
git clone https://github.com/\$(gh api user -q .login)/${PROJ}.git
cd ${PROJ}
./scripts/setup.sh
\`\`\`

## Directory Structure

\`\`\`
${PROJ}/
├── scripts/      # Automation scripts
├── docs/         # Documentation
├── help/         # Help assets
├── files/        # Data files
├── assets/       # Media assets
├── src/          # Source code
├── tests/        # Test suite
└── .github/      # GitHub configs
\`\`\`

## License

MIT - See LICENSE file
EOF

    # ROADMAP.md
    cat > "${BUILD_DIR}/docs/ROADMAP.md" <<EOF
# Development Roadmap

## Phase 1: Foundation ✅
- [x] Repository structure
- [x] Documentation scaffolding
- [x] Asset pipeline setup

## Phase 2: Core Features ⏳
- [ ] Main script implementation
- [ ] Configuration management
- [ ] Error handling

## Phase 3: Integration ⏳
- [ ] API integrations
- [ ] Help system
- [ ] Asset processing

## Phase 4: Polish ⏳
- [ ] Performance optimization
- [ ] Comprehensive testing
- [ ] Production deployment
EOF

    # CONTRIBUTING.md
    cat > "${BUILD_DIR}/docs/CONTRIBUTING.md" <<EOF
# Contributing Guidelines

## How to Contribute

1. Fork the repository
2. Create a feature branch (\`git checkout -b feature/amazing-feature\`)
3. Make your changes
4. Run tests (\`./scripts/test.sh\`)
5. Commit and push
6. Open a Pull Request

## Code Standards

- Follow existing code style
- Write meaningful commit messages
- Add tests for new features
- Update documentation
EOF

    # .gitignore
    cat > "${BUILD_DIR}/.gitignore" <<EOF
# Dependencies
node_modules/
vendor/

# Build outputs
dist/
build/
*.pyc
__pycache__/

# Environment
.env
.env.local
*.log

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Secrets
*.pem
*.key
secrets/
EOF

    # Sample script
    cat > "${BUILD_DIR}/scripts/setup.sh" <<'EOF'
#!/bin/bash
set -euo pipefail
echo "Setting up ${PROJ}..."
echo "Installing dependencies..."
echo "Configuration complete!"
EOF
    chmod +x "${BUILD_DIR}/scripts/setup.sh"

    # GitHub Actions workflow
    cat > "${BUILD_DIR}/.github/workflows/ci.yml" <<EOF
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run setup
        run: echo "Build successful"
EOF

    #---------------------------------------------------------------------------
    # 4. Verify Build
    #---------------------------------------------------------------------------
    log_step "Verifying build integrity..."
    local file_count=$(find "${BUILD_DIR}" -type f | wc -l)
    local dir_count=$(find "${BUILD_DIR}" -type d | wc -l)
    log_info "Created ${file_count} files in ${dir_count} directories"

    if [[ "$DRY_RUN" == "--dry-run" ]]; then
        log_warn "DRY RUN COMPLETE - No remote changes made"
        log_info "Build directory: ${BUILD_DIR}"
        tree "${BUILD_DIR}" 2>/dev/null || find "${BUILD_DIR}" -print | head -30
        exit 0
    fi

    #---------------------------------------------------------------------------
    # 5. Git Operations
    #---------------------------------------------------------------------------
    log_step "Initializing Git repository..."
    cd "${BUILD_DIR}"
    git init -q
    git config user.name "Turbo-Fleet-Worker"
    git config user.email "fleet@turbo-the-tech-dev.dev"
    
    log_step "Staging files..."
    git add .
    
    log_step "Creating initial commit..."
    git commit -m "System: full structural bootstrap

- Directory structure created
- Documentation scaffolded
- CI/CD pipeline configured
- Index.html privacy files deployed

Generated by bootstrap-repo.sh" -q

    #---------------------------------------------------------------------------
    # 6. Remote Deployment
    #---------------------------------------------------------------------------
    log_step "Creating remote repository..."
    gh repo create "${PROJ}" "${VISIBILITY}" --source=. --remote=origin --push

    local username=$(gh api user -q .login)
    local repo_url="https://github.com/${username}/${PROJ}"

    #---------------------------------------------------------------------------
    # 7. Success
    #---------------------------------------------------------------------------
    log_success "Deployment successful!"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Repository: ${repo_url}"
    echo "  Clone: git clone ${repo_url}.git"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
}

# Run main function
main "$@"
